# Generated by Django 5.2.6 on 2026-03-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_migrate_name_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="_first_name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="_last_name",
            field=models.TextField(max_length=255),
        ),
    ]
