# Generated by Django 5.2.6 on 2025-10-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="min_qty_on_stock",
            field=models.IntegerField(default=0),
        ),
    ]
