# Generated by Django 5.2.6 on 2025-10-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_product_min_qty_on_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="min_qty_on_stock",
            field=models.IntegerField(
                default=0,
                help_text="Minimalna ilość produktu, która powinna być na stanie magazynowym",
            ),
        ),
    ]
