# Generated by Django 5.2.6 on 2025-11-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_product_min_qty_on_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("size", models.CharField(blank=True, max_length=20, null=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_qty_on_stock", models.IntegerField(default=0)),
                ("period_days", models.IntegerField(default=365)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.productcategory",
                    ),
                ),
            ],
        ),
    ]
