# Generated by Django 5.2.6 on 2025-11-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_pendingproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingproduct",
            name="category",
            field=models.ForeignKey(
                default="clothing",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.productcategory",
            ),
        ),
    ]
