# Generated by Django 5.2.6 on 2025-09-21 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Przyjęcie"),
                            ("out", "Wydanie"),
                            ("adjustment", "Korekta"),
                            ("return", "Zwrot"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("document_type", models.CharField(max_length=50)),
                ("document_id", models.IntegerField()),
                ("movement_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-movement_date"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=20, null=True)),
                ("quantity", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse Stock",
                "verbose_name_plural": "Warehouse Stocks",
                "unique_together": {("product", "size")},
            },
        ),
    ]
