# Generated by Django 5.2.6 on 2025-10-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="document_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
