# Generated by Django 5.2.6 on 2025-12-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_stockmovement_document_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("in", "Przyjęcie"),
                    ("out", "Wydanie"),
                    ("adjustment", "Korekta"),
                    ("return", "Zwrot"),
                    ("stock_correction ", "Korekta stanu magazynowego"),
                ],
                max_length=17,
            ),
        ),
    ]
