# Generated by Django 5.2.6 on 2025-10-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_documentitem_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentitem",
            name="total_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=12, null=True
            ),
        ),
    ]
