# Generated by Django 5.2.6 on 2025-11-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_pendingproduct_category"),
        ("documents", "0003_documentitem_total_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingReceiptDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(max_length=255)),
                ("recipient", models.CharField(blank=True, max_length=255, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("raw_json", models.JSONField()),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PendingReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity_ordered", models.IntegerField(default=0)),
                ("quantity_delivered", models.IntegerField(default=0)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True)),
                ("code", models.CharField(max_length=50)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.pendingreceiptdocument",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
            ],
        ),
    ]
