# Generated by Django 5.2.6 on 2025-11-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_pendingreceiptdocument_pendingreceiptitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingreceiptdocument",
            name="raw_json",
        ),
    ]
