# Generated by Django 5.2.6 on 2025-11-29 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_pendingproduct_category"),
        ("documents", "0005_remove_pendingreceiptdocument_raw_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingreceiptdocument",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="pendingreceiptdocument",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.supplier",
            ),
        ),
    ]
