# Generated by Django 5.2.6 on 2025-12-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_pendingproduct_category"),
        ("documents", "0007_invoicedocument_invoicelineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicelineitem",
            name="pending_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.pendingproduct",
            ),
        ),
    ]
