# Generated by Django 5.2.6 on 2025-12-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_invoicelineitem_pending_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicelineitem",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
