# Generated by Django 5.2.6 on 2025-12-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_invoicelineitem_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingreceiptdocument",
            name="order_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
